language: ruby

before_install:
  - yes | gem update --system --force
  - gem install bundler

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec

services:
  - postgresql

addons:
  postgresql: '12.2'

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

addons:
  postgresql: '12.2'

env:
  - ENV['RAILS_ENV'] = 'test'
