language: ruby

before_install:
  - yes | gem update --system --force
  - gem install bundler

addons:
  postgresql: '12.2'

before_script:
  # - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

services:
  - postgresql

addons:
  postgresql: '12.2'

env:
  - ENV['RAILS_ENV'] = 'test'
