language: ruby
os: osx

before_install:
  - yes | gem update --system --force
  - gem install bundler

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  - ENV['RAILS_ENV'] = 'test'
