language: ruby
os: osx

services: 
  - postgresql 

before_script: 
  - psql -c 'create database travis_ci_test;' -U postgres 

env:
  - ENV['RAILS_ENV'] = 'test'

before_install:
  - gem install rake
